kind: pipeline
type: docker
name: deployment

clone:
  disable: false

steps:

- name: build
  image: alpinelinux/docker-cli
  environment:
    DOCKER_HOST: tcp://192.168.2.10:2375
  commands:
  - docker build -t "tickets:latest" .
  - docker tag tickets:latest 192.168.2.10:5000/tickets:latest
  - docker push 192.168.2.10:5000/tickets:latest
  when:
    event:
    - pull_request
    - push
    - custom
    branch:
    - main


- name: destroy
  image: alpinelinux/docker-cli
  failure: ignore
  environment:
    DOCKER_HOST: tcp://192.168.2.10:2375
  commands:
  - docker stop tickets
  - docker rm tickets
  when:
    event:
    - pull_request
    - push
    - custom
    branch:
    - main

- name: deploy
  image: alpinelinux/docker-cli
  environment:
    DOCKER_HOST: tcp://192.168.2.10:2375
    TOKEN:
      from_secret: tickets_token
  commands:
  - docker pull 192.168.2.10:5000/tickets:latest
  - docker run -d --name tickets --restart "unless-stopped" --network bridge -e "TOKEN"="$TOKEN" -v "tickets":"/configuration" 192.168.2.10:5000/tickets:latest
  when:
    event:
    - pull_request
    - push
    - custom
    branch:
    - main